# Generated by Django 4.2 on 2024-09-12 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('yandex', 'Yandex'), ('mail', 'Mail.ru')], max_length=100)),
                ('last_fetched', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailaccount')),
            ],
        ),
    ]
