# Generated by Django 4.2 on 2024-09-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField()),
                ('received_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('attachments', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('yandex', 'Yandex'), ('mail', 'Mail.ru')], max_length=100),
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
        migrations.AddField(
            model_name='message',
            name='email_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailaccount'),
        ),
    ]
