# Generated by Django 4.2 on 2024-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_message_alter_emailaccount_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
