# Generated by Django 4.2 on 2024-09-12 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_message_received_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='last_fetched',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
