# Generated by Django 4.2 on 2024-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailaccount_last_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
